apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuito-work
spec:
  selector:
    matchLabels:
      app: yuito-work
  template:
    metadata:
      labels:
        app: yuito-work
    spec:
      containers:
        - name: yuito-work
          image: localhost:32000/yuito-work:0.3.1
          envFrom:
          - secretRef:
              name: spotify
              optional: true
          ports:
            - containerPort: 3000
