apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuito-work
  labels:
    app: yuito-work
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yuito-work
  template:
    metadata:
      labels:
        app: yuito-work
    spec:
      containers:
        - name: yuito-work
          image: registry.uniproject.jp/yuito-it/yuito-work:3.2.1
          envFrom:
            - secretRef:
                name: spotify
                optional: true
          volumeMounts:
            - name: spotify
              mountPath: /app/tmp
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: harbor-registry-secret
      volumes:
        - name: spotify
          persistentVolumeClaim:
            claimName: spotify
