apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuito-work
  labels:
    app: yuito-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuito-work
  template:
    metadata:
      labels:
        app: yuito-work
    spec:
      containers:
        - name: yuito-work
          image: localhost:32000/yuito-work:1.2.1
          envFrom:
          - secretRef:
              name: spotify
              optional: true
          volumeMounts:
          - name: spotify
            mountPath: /app/tmp
          ports:
            - containerPort: 3000
      volumes:
      - name: spotify
        persistentVolumeClaim:
          claimName: spotify
