apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yuito-work
  labels:
    name: yuito-work
spec:
  ingressClassName: nginx
  rules:
  - host: yuito.work
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: yuito-work
            port: 
              number: 80
