apiVersion: v1
kind: PersistentVolume
metadata:
  name: spotify-yuito-site
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/users/yuito/site/spotify
    server: nfs.unipro.infra
  claimRef:
    namespace: yuito-site
    name: spotify
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotify
spec:
  resources:
    requests:
      storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: spotify-yuito-site
