---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBqD/VU0VUpEE96Pl2eTEzQrYvAmnvoicnaho0vi77gbTwyxKQMk4M5M/KLLXdCtnh9Q0z7nJK2MNqMGaeOuM/CtqDF62TBRg0DRLjFeHbf7xpDKvHJiyLBxsDqvnPObsa6ZpBAAwi7dxbC2XuXnXQCOdqiGK+uU5lQGZgNQ/g/ReC59F9N5aPMsGMO73CQKpnc4bcbP1uWoe6DY/mkDNFLoH7aje64VX/Bxz/3kjdKN7Qbpf2Kyzjh5c3EYXeyGP2xr92GDze+udCdALG1ePAdKRnq+MCQYybCwGtnHvUajhwEXDbobEYCgeJTnvTNo3981yDoSXNG+wLYNmE1N+t3YoDRtf6rCil/1+m2kymp7tJH/9ENhWB4IaQNvE1zwcM2ydVF3fDuXWKhqAQ0F/A086w+L3xilk0/5I6tBqFt4M1r8VbrfUzVOPNkoMGXRsVQpCZtZRKMSB1Si/EteWHlFZOdn7ePtKvaeKP0rKy2uMmX0VTMRMX6kKyoa6Pdpj2dBjmflNvyysrCWrUpxMq/2mPD9aWCBgsiBCMWRNqCB6j4IojCSrXc/K4sIFZ7m5mCzLjU9cnAF/50z9PEv4RyyUPNZjacR+W9uDnMpiv+0YpTsLhk28/4UFHRMVwn5CRTbjppuf+Yob+5Ko8kNVGzzHJC39tB+c5Y7R2F0wBDelduKc0vNrstt2EHD2jaEZ9fGak3i9yJg6RCx8UTBf4s2kwdhP0fHBUUA2OKnW9VF+V4O8wA+rgTDDx0HHT84a5qGpcO2UO4fTHkhW8HaaANGYLl8p3TMJy6ErwvVPxrOha3z5Y9Js1D85YvHjRUHFG40cJ01YKoLncVTF6Tlpr9byF/lBicDfIRqasGd265ILlY+B/guNcWpiuSIDMM6/ggT0azS9Z5gYkkm5Inp9q2MBDh1pXPmJIb2eCbDg7Lm7ocGGDwAnlWIet1/MnADygXnQ4L8Kcd73UhRdaf
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
