apiVersion: v1
kind: ConfigMap
metadata:
  name: rvp-config
data:
  config.yaml: |
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    error_log /var/log/nginx/error.log;
    include /etc/nginx/modules-enabled/*.conf;

    events {
    	worker_connections 768;
    	# multi_accept on;
    }

    http {

    	##
    	# Basic Settings
    	##

    	sendfile on;
    	tcp_nopush on;
    	types_hash_max_size 2048;
    	# server_tokens off;

    	# server_names_hash_bucket_size 64;
    	# server_name_in_redirect off;

    	include /etc/nginx/mime.types;
    	default_type application/octet-stream;

    	##
    	# SSL Settings
    	##

    	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
    	ssl_prefer_server_ciphers on;

    	##
    	# Logging Settings
    	##

    	access_log /var/log/nginx/access.log;

    	##
    	# Gzip Settings
    	##

    	gzip on;

    	# gzip_vary on;
    	# gzip_proxied any;
    	# gzip_comp_level 6;
    	# gzip_buffers 16 8k;
    	# gzip_http_version 1.1;
    	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    	##
    	# Virtual Host Configs
    	##

    	include /etc/nginx/conf.d/*.conf;
      include /etc/nginx/sites-enabled/*.conf;
    }
  site.conf: |
    server {
    listen       80;
    server_name  www.yuito-it.jp;
    server_name  yuito-it.jp;
    server_name  www.yuito.work;
    server_name  yuito.work;
    return 301 https://ゆいと.jp$request_uri;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rvp
spec:
  selector:
    matchLabels:
      app: nginx-rvp
  template:
    metadata:
      labels:
        app: nginx-rvp
    spec:
      containers:
        - name: nginx-rvp
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: rvp-config
              mountPath: /etc/nginx/nginx.conf
              subPath: config.yaml
            - name: rvp-config
              mountPath: /etc/nginx/sites-enabled/site.conf
              subPath: site.conf
      volumes:
        - name: rvp-config
          configMap:
            name: rvp-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rvp
spec:
  selector:
    app: nginx-rvp
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yuito-site-old-ingress
  namespace: yuito-work
  annotations:
    cert-manager.io/cluster-issuer: le-cf-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ngins.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: www.yuito.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-rvp
                port:
                  number: 80
    - host: www.yuito-it.jp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-rvp
                port:
                  number: 80
  tls:
    - hosts:
        - www.yuito.work
        - yuito.wotk
        - yuito-it.jp
        - www.yuito-it.jp
      secretName: unipro-www-old-tls
